package controller;

import java.io.IOException;

/**NewScene is a functional interface*/
public interface NewScene {

    /**Method for creating and displaying new scene
     * @param someView fxml file for new scene
     * @throws IOException generated by FXML loader
     */
    void newScene(String someView) throws IOException;

}
