package controller;

import java.sql.SQLException;

/**Report is a functional interface*/
public interface Report {

    /**Method for calculating a customer's number of scheduled appointments
     * @param customerName name of customer you're counting appointments for
     * @return returns a string representation of the count
     * @throws SQLException generated by SQL query to county # of appointments
     */
    String calculateNumApps(String customerName) throws SQLException;

}

